openapi: 3.0.3
info:
  title: API тестовое
  version: "1.0"
servers:
  - url: http://localhost:8080
tags:
  - name: AdminPanel
    description: Description
paths:
  /moderate/v1:
    patch:
      summary: Запрос на смену статуса карточки со словом
      operationId: moderate
      tags:
        - AdminPanel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardModerationReq'
        required: true
      responses:
        '200':
          description: ALL IS OK
        '400':
          description: BAD REQUEST
components:
  schemas:
    CardModerationReq:
      description: SOME DESC
      type: object
      properties:
        word:
          type: string
        translate:
          type: string
