scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.128:8081'] #change on your ip, (ipconfig etc.) or use host.docker.internal
  - job_name: postgresql
    static_configs:
      - targets: [ '192.168.0.128:9187' ] #change on your ip, (ipconfig etc.) or use host.docker.internal