#Database configuration
create table Person(
    id int primary key generated by default as identity,
    username varchar(40)
);
create table Dictionary(
       id int primary key generated by default as identity,
       name varchar(50),
       owner_id int references Person(id) unique
);
create table Word(
    id int primary key generated by default as identity,
    value varchar,
    translate varchar,
    dictionary_id int references Dictionary(id)
);
alter table Person add column dictionary_id int references Dictionary(id) unique;
alter table dictionary drop constraint dictionary_owner_id_fkey, add constraint dictionary_owner_id_fkey foreign key (owner_id) references person(id) on delete cascade;
