create table Person(
    id int primary key generated by default as identity,
    username varchar(40),
    password varchar,
    role varchar,
    created_at timestamp without time zone
);
create table Dictionary(
       id int primary key generated by default as identity,
       name varchar(50),
       owner_id int references Person(id) on delete cascade unique
);
create table Word(
    id int primary key generated by default as identity,
    value varchar,
    translate varchar,
    dictionary_id int references Dictionary(id)
);
insert into person(username, password, role) values('admin','$2a$10$O2pPmmB.XLvrOWyFvw0GteYnoGzAR8tEODu1eHKx3sSTENF.ALvdS','ROLE_ADMIN');
insert into word(dictionary_id,translate,value) values(1,'Лягушка','Frog'),(1,'Бревно','Log'),(1,'Топор','Axe'),(1,'Кот','Cat'),(1,'Дерево','Tree');