create table Person(
    id int primary key generated by default as identity,
    username varchar(40) check ( length(username) >= 1 and length(username) <= 40 ),
    password varchar not null,
    role varchar(15),
    created_at timestamp without time zone
);
create table Word(
    id int primary key generated by default as identity,
    value varchar,
    translate varchar
);
insert into person(username, password, role) values('admin','$2a$10$O2pPmmB.XLvrOWyFvw0GteYnoGzAR8tEODu1eHKx3sSTENF.ALvdS','ROLE_ADMIN');
insert into word(translate,value) values('Лягушка','Frog'),('Бревно','Log'),('Топор','Axe'),('Кот','Cat'),('Дерево','Tree');